Repository acmucsd/membership-portal, pull requests merged in 2023-03, with the labels that each got.

#330 Create .nvmrc
  .nvmrc
Labels: DevOps

#323 Implement user handles
  api/controllers/UserController.ts
  api/decorators/Validators.ts
  api/validators/AuthControllerRequests.ts
  api/validators/GenericRequests.ts
  api/validators/UserControllerRequests.ts
  migrations/0036-add-handle-column-to-users-table.ts
  models/UserModel.ts
  package.json
  repositories/UserRepository.ts
  services/UserAccountService.ts
  services/UserAuthService.ts
  tests/auth.test.ts
  tests/data/UserFactory.ts
  tests/data/UserRegistrationFactory.ts
  tests/user.handles.test.ts
  types/ApiRequests.ts
  types/ApiResponses.ts
Labels: Users, Good First Issue

#337 Update .env.example
  .env.example
Labels: Good First Issue
